SCR_SET_MODE		EQU $BC0E
SCR_SET_INK		EQU $BC32
SCR_SET_BORDER		EQU $BC38

GRA_MOVE_ABSOLUTE	EQU $BBC0
GRA_MOVE_RELATIVE	EQU $BBC3
GRA_SET_ORIGIN		EQU $BBC9

GRA_LINE_ABSOLUTE	EQU $BBF6
GRA_LINE_RELATIVE	EQU $BBF9

GRA_FILL		EQU $BD52
GRA_SET_PEN		EQU $BBDE
